### ISSUE TITLE
Link to example applications

### ISSUE THREAD

**Issue by theborakompanioni** [xmolecules/jmolecules-examples#1]
Will this repo contain example applications or a collection of links to example applications?

If the latter, it'd be awesome to include: `lnurl-auth-example-application`
https://github.com/theborakompanioni/bitcoin-spring-boot-starter/tree/master/examples/incubator/lnurl-auth-example-application

I am still learning about ddd, so maybe the code is not exemplary/best practice.
Thank you. Have a nice day.

**Comment by odrotbohm** [comment]
Nice one, I'll add a section in the readme to point to well-crafted examples!
